### ISSUE TITLE
Metadata for articles

### ISSUE THREAD

**Issue by lmullen** [chnm/model-articles#10]
I think we will need a bit more metadata for each of the articles. 

- [ ] We need some way of tracking the original citation. We can either just have that as a single field (though it probably needs to be HTML formatted) or as separate pieces that the template puts together.

@srob4757 Any things else we need to display about these articles? The question of how to cite this site and the articles in it is a bit tricky.

**Comment by lmullen** [comment]
- [ ] Another field we might need (see the design of article header section) is type of article: preprint, postprint, etc.

**Comment by srob4757** [comment]
I agree we definitely need type of article - making clear that the article text is preprint is key.

**Comment by srob4757** [comment]
Several of the journals I've published in specify how they want preprints to be identified - I'll take a look at those that will appear on the site. I have a feeling that the format is not standard across all journals...

**Comment by lmullen** [comment]
Is it correct that _all_ of the articles contributed will be preprints? We don't have any post prints or so on?

**Comment by srob4757** [comment]
I think there was only one that wasn't going to be a preprint and that fell through - I'll check

**Comment by lmullen** [comment]
@kalbers Because citations can end up being messy the simplest thing to do might be to add a single field to the YAML, like this.

```
citation: 'Funk, Kellen, and Lincoln A. Mullen. "The Spine of American Law: Digital Text Analysis and U.S. Legal Practice," <em>American Historical Review</em> 123, no. 1 (2018): 132&ndash;164, <a href="https://doi.org/10.1093/ ahr/123.1.132">https://doi.org/10.1093/ ahr/123.1.132</a>.'
```

And then you can then just render that single field in the template. There is a way to just render HTML and not have it escaped in Hugo; I don't know it offhand but I can look it up if need be.

That's maybe not as elegant as it could be, but it might be simplest. 

If you want to break apart the pieces, then metadata properties like this could work

- citation-authors
- citation-title
- citation-journal
- citation-year
- citation-volume
- citation-issue
- citation-pages
- citation-doi
