### ISSUE TITLE
Design of annotations

### ISSUE THREAD

**Issue by lmullen** [chnm/model-articles#14]
I like the headings, and the boldness of the annotations. A few suggestions.

- [ ] The color of the annotations seems just a bit too bright to me. But I don't know anything about colors; your call, @kalbers.
- [ ] It's not immediately clear that the annotations are clickable. Could some kind of icon (or text "expand") make that clearer?
- [ ] Seems like the annotations need some vertical margin above and below, both when expanded and not. 

The Barletta example is missing a headnote. @srob4757 and I probably need to get that from him. But design wise, will that be normal, expandable annotation? Or an annotation which is always open? Should that replace the abstract?

**Comment by srob4757** [comment]
Making the headnote always open might help signal that the annotated article is something other than just an article. And if it replaces the abstract that will be a further signal

**Comment by lmullen** [comment]
I think I like that approach, if @kalbers thinks it is good and workable.

**Comment by kalbers** [comment]
Include text explaining annotations in the headnote and have the headnote at the top.

**Comment by srob4757** [comment]
I want to second Lincoln on those earlier points about the style of the annotations
- the red is too bright for me, too jarring a contrast. Maybe some transparency?
- there needs to be some indication the annotations can be expanded
Can we also offset the annotations somehow - my first reaction was that they were subtitles, so I think we need to take them out of the flow of the article text

**Comment by kalbers** [comment]
I did push up a new design/color scheme for a few things, including the site header and the annotations. Let me know what you think of the changes.

**Comment by lmullen** [comment]
I think the triangle and the orange are an improvement.

**Comment by srob4757** [comment]
I also like the triangle and the orange. I do still think the annotations scan as subheadings, especially if you haven't encountered a subheading as with the Barleta article. I'm not sure what options there are to align the annotations differently so they don't scan as part of the text - could the annotation extend across the right margin? And/or could the title of the annotation be aligned right rather than centered?
