### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by lmullen** [chnm/model-articles#2]
@srob4757 What title do we want to use for the site? `Model Articles` seems a little stark and unexplained.

**Comment by srob4757** [comment]
The formal title of the project is "Arguing with Digital History: Models of argument-driven digital history," which I quite like - I think we could get away with the pre-colon title, but the post-colon title is ok with me if you prefer something more literal

**Comment by lmullen** [comment]
I think we would be clear to modify the title of the grant for clarity in this site. How about just the subtitle for this site? `Models of argument-driven digital history`?

**Comment by srob4757** [comment]
OK with me

**Comment by lmullen** [comment]
Then let's go with that, please, @kalbers.
