### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by lmullen** [chnm/model-articles#6]
- [ ] The footer needs to have the GMU and RRCHNM logos. (These are broken when I run the site.)
- [ ] The footer also needs the Mellon logo, above the GMU and RRCHNM logos. @kalbers Do you need text for that?

**Comment by lmullen** [comment]
- [ ] We need to replace the CRDH text in the footer with the text for this project. @srob4757 any preferences?

**Comment by kalbers** [comment]
I'm having trouble finding info from Mellon about how to implement the logo and/or where to download it from. Is that mentioned in the grant info anywhere?

**Comment by srob4757** [comment]
Nothing in the grant info - I think for other projects we've just used logos from the Mellon site (although I don't see those on the current versions of the Omeka and Tropy sites)

**Comment by kalbers** [comment]
Leave logo out. Add a credit.
